controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rebel_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rebel_gripper_controller:
  ros__parameters:
    joints:
      - gripper_gear_left_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 100.0
    action_monitor_rate: 100.0
    
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 30.0
