#!/usr/bin/env python3
"""Light the simulated stack light's tiers to match the real one.

On the rover the three tiers are LEDs on Teensy GPIOs. In Gazebo they are three
coloured cylinders in stacklight.xacro, and a cylinder does not glow - so
without this the simulated rover carries a stack light that never changes,
which is worse than none: it looks like a working indicator and reports
nothing.

This subscribes to the same /stacklight_subscription the firmware does, and
turns each tier's material up or down through gz's MaterialColor command:

    /stacklight_subscription (std_msgs/UInt8)
        -> /world/<world>/material_color (ros_gz_interfaces/MaterialColor)
        -> bridged to gz, applied by the UserCommands system

Simulation only. It is a viewer, not a controller - it never decides a colour,
it only shows the one stacklight.py already chose, so the two can never
disagree about what the rover is doing.

ADDRESSING THE TIERS. MaterialColor takes an entity NAME, and sdformat renames
a URDF visual on the way in: <lump>_fixed_joint_lump__<visual name>_visual_<n>.
stacklight.xacro keeps stacklight_joint out of base_link's lump precisely so
that <n> counts only that link's own five visuals - lumped into base_footprint
they came out as _6.._10 and adding one visual anywhere else on the chassis
would have renumbered them silently. The names below are still generated, not
declared, so test_stacklight.py runs the real xacro through `gz sdf -p` and
asserts each one exists. A rename breaks the test, not the light.

WHY IT REPUBLISHES. Every incoming state is applied, not just the changes.
MaterialColor is a one-shot command, so anything that misses it - the node
running before gz, a respawned model, a reset world - stays wrong until the
next command. stacklight.py refreshes at 1 Hz, so this re-asserts at 1 Hz too,
and any of those cases self-corrects within a second.
"""

import rclpy
from rclpy.node import Node
from ros_gz_interfaces.msg import Entity, MaterialColor
from std_msgs.msg import ColorRGBA, UInt8


# The firmware's enum, and stacklight.py's COLOR_CODES. test_stacklight.py
# pins all three together.
COLOR_CODES = {"red": 1, "yellow": 2, "green": 3, "off": 4}

# Tier -> the colour it shows when lit, matching the materials in
# stacklight.xacro so a tier at rest looks like the part it represents.
TIER_COLORS = {
    "red": (0.90, 0.10, 0.10),
    "yellow": (0.95, 0.65, 0.05),
    "green": (0.10, 0.80, 0.25),
}


class StacklightGzVisual(Node):
    def __init__(self):
        super().__init__("stacklight_gz_visual")

        self.declare_parameter("state_topic", "/stacklight_subscription")
        # World-scoped, like every other world topic in the bridge configs.
        # aries/config/gazebo_bridge.yaml is 'empty'; marsyard is 'leo_marsyard'.
        self.declare_parameter("material_color_topic", "/world/empty/material_color")

        # SDF visual names, "<tier>:<name>". Generated by sdformat - see the
        # module docstring, and the test that pins them.
        self.declare_parameter("tier_visuals", [
            "red:stacklight_link_fixed_joint_lump__stacklight_red_visual_3",
            "yellow:stacklight_link_fixed_joint_lump__stacklight_amber_visual_2",
            "green:stacklight_link_fixed_joint_lump__stacklight_green_visual_1",
        ])

        # An unlit tier is not black - it is a coloured lens with nothing behind
        # it, so it keeps its hue at a fraction of the brightness. Black tiers
        # read as missing rather than off.
        self.declare_parameter("unlit_scale", 0.30)
        # Emissive is what actually makes it look lit: diffuse alone just
        # follows the scene lighting, and in a shadowed corner a "lit" tier
        # would stay dull.
        self.declare_parameter("emissive_scale", 0.85)

        g = self.get_parameter
        self.unlit_scale = float(g("unlit_scale").value)
        self.emissive_scale = float(g("emissive_scale").value)

        self.tiers = {}
        for entry in g("tier_visuals").value:
            if not entry:
                continue
            tier, _, name = str(entry).partition(":")
            tier, name = tier.strip(), name.strip()
            if tier not in TIER_COLORS:
                raise ValueError(
                    f"stacklight_gz_visual: unknown tier {tier!r}; "
                    f"known tiers are {sorted(TIER_COLORS)}")
            self.tiers[tier] = name
        if not self.tiers:
            raise ValueError("stacklight_gz_visual: tier_visuals is empty")

        self.pub = self.create_publisher(
            MaterialColor, str(g("material_color_topic").value), 10)
        self.create_subscription(
            UInt8, str(g("state_topic").value), self._state_cb, 10)

        self.lit = None
        self.get_logger().info(
            f"Stacklight sim visuals -> {self.pub.topic_name}: "
            + ", ".join(f"{t}={n}" for t, n in self.tiers.items()))

    def _state_cb(self, msg):
        lit = self._tier_for(int(msg.data))
        if lit != self.lit:
            self.get_logger().info(f"tier lit: {lit or 'none'}")
            self.lit = lit
        for tier, visual in self.tiers.items():
            self.pub.publish(self._command(visual, TIER_COLORS[tier], tier == lit))

    def _tier_for(self, code):
        """Which tier a wire value lights. Unknown values light red, the same
        fail-safe the firmware's switch default takes."""
        for tier, value in COLOR_CODES.items():
            if value == code:
                return None if tier == "off" else tier
        return "red"

    def _command(self, visual, rgb, lit):
        r, g, b = rgb
        msg = MaterialColor()
        msg.entity.name = visual
        msg.entity.type = Entity.VISUAL
        # ALL, not FIRST: FIRST stops at whichever entity the ECM happens to
        # return first, and these names appear once per spawned robot.
        msg.entity_match = MaterialColor.ALL

        scale = 1.0 if lit else self.unlit_scale
        body = ColorRGBA(r=r * scale, g=g * scale, b=b * scale, a=1.0)
        msg.ambient = body
        msg.diffuse = body
        msg.specular = ColorRGBA(r=0.1, g=0.1, b=0.1, a=1.0)
        e = self.emissive_scale if lit else 0.0
        msg.emissive = ColorRGBA(r=r * e, g=g * e, b=b * e, a=1.0)
        return msg


def main(args=None):
    rclpy.init(args=args)
    node = StacklightGzVisual()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
