<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aries_bringup</name>
  <version>0.1.0</version>
  <description>Bringup launch wrappers for Aries robot workflows.</description>

  <maintainer email="shreyaspatel517@gmail.com">shreyas</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>aries</exec_depend>
  <exec_depend>aries_moveit</exec_depend>
  <exec_depend>aries_vision_grasp</exec_depend>
  <exec_depend>aries_common</exec_depend>
  <exec_depend>aries_lidar</exec_depend>
  <exec_depend>aries_imu</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rover_nav</exec_depend>
  <exec_depend>odrive_can</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <!-- pip3 install evdev  (or: sudo apt install python3-evdev) -->
  <exec_depend>python3-evdev</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>controller_manager_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
</package>
